### ISSUE TITLE
This scorex support qora-like pos?

### ISSUE THREAD

**Issue by soliury** [input-output-hk/Scorex#115]
> Two 100% Proof-of-Stake consensus algos out of the box, Nxt-like and Qora-like. One algo could be replaced with an another with just one line of code edited.

Happen to see the qora in readme. but , nxt is still alive, qora is dead. Can you explain more about the qora alog?

**Comment by kushti** [comment]
Scorex is modular framework consisting of a core and also modules implementing concrete functionality. Proof-of-Stake module(going along with Scorex code) supports Qora-like pure Proof-of-Stake consensus algo, yes. The code is more or less the same as Qora consensus code as of beginning of 2015. I can't say much about details now, but its not very different from Nxt imho.
